// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuUhc3e0Qy5cNgCWRRIVI0pKdr42NEHY',
    appId: '1:293079007321:web:c6d4b15aa715ec2217b148',
    messagingSenderId: '293079007321',
    projectId: 'projectim-69233',
    authDomain: 'projectim-69233.firebaseapp.com',
    storageBucket: 'projectim-69233.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuUhc3e0Qy5cNgCWRRIVI0pKdr42NEHY',
    appId: '1:293079007321:android:c6d4b15aa715ec2217b148',
    messagingSenderId: '293079007321',
    projectId: 'projectim-69233',
    storageBucket: 'projectim-69233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuUhc3e0Qy5cNgCWRRIVI0pKdr42NEHY',
    appId: '1:293079007321:ios:c6d4b15aa715ec2217b148',
    messagingSenderId: '293079007321',
    projectId: 'projectim-69233',
    storageBucket: 'projectim-69233.firebasestorage.app',
    iosBundleId: 'com.im.chatTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuUhc3e0Qy5cNgCWRRIVI0pKdr42NEHY',
    appId: '1:293079007321:macos:c6d4b15aa715ec2217b148',
    messagingSenderId: '293079007321',
    projectId: 'projectim-69233',
    storageBucket: 'projectim-69233.firebasestorage.app',
    iosBundleId: 'com.im.chatTalk',
  );
}
